#!/usr/bin/env bash
#
# Build the Linux virglrenderer bundle used by smolvm's virtio-gpu/Venus path.
# Run natively on Ubuntu 22.04 for the target architecture so the resulting
# libraries retain the release's glibc 2.35 compatibility floor.
#
# Usage:
#   ./scripts/build-virglrenderer-linux.sh [OUTPUT_DIR]
#
# OUTPUT_DIR defaults to lib/linux-$(uname -m). The script installs no packages;
# callers must provide Meson, Ninja, a C compiler, pkg-config, and the EGL/GBM,
# epoxy, Vulkan, and Python YAML development dependencies.
set -euo pipefail

VERSION="1.2.0"
SOURCE_SHA256="47a64189492a754685a430c713ac6700f4b1c3e7b871e87889ddb96e4d65e8ab"
SOURCE_URL="https://gitlab.freedesktop.org/virgl/virglrenderer/-/archive/virglrenderer-${VERSION}/virglrenderer-virglrenderer-${VERSION}.tar.bz2"

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ARCH="$(uname -m)"
case "$ARCH" in
    x86_64 | aarch64) ;;
    *)
        echo "error: unsupported Linux architecture: $ARCH" >&2
        exit 1
        ;;
esac

if [[ "$(uname -s)" != "Linux" ]]; then
    echo "error: virglrenderer Linux bundles must be built natively on Linux" >&2
    exit 1
fi

OUTPUT_DIR="${1:-$REPO_ROOT/lib/linux-$ARCH}"
mkdir -p "$OUTPUT_DIR"
OUTPUT_DIR="$(cd "$OUTPUT_DIR" && pwd)"

for command in curl meson ninja pkg-config sha256sum tar; do
    command -v "$command" >/dev/null 2>&1 || {
        echo "error: required command not found: $command" >&2
        exit 1
    }
done

WORK_DIR="$(mktemp -d)"
trap 'rm -rf "$WORK_DIR"' EXIT

ARCHIVE="$WORK_DIR/virglrenderer-${VERSION}.tar.bz2"
echo "Downloading virglrenderer ${VERSION}..."
curl --fail --location --retry 3 --silent --show-error \
    "$SOURCE_URL" -o "$ARCHIVE"
echo "${SOURCE_SHA256}  ${ARCHIVE}" | sha256sum --check -

tar -xjf "$ARCHIVE" -C "$WORK_DIR"
SOURCE_DIR="$WORK_DIR/virglrenderer-virglrenderer-${VERSION}"
BUILD_DIR="$WORK_DIR/build"
STAGE_DIR="$WORK_DIR/stage"

echo "Configuring virglrenderer ${VERSION} for linux-${ARCH}..."
meson setup "$BUILD_DIR" "$SOURCE_DIR" \
    --buildtype=release \
    --prefix=/usr \
    --libdir=lib \
    --libexecdir=libexec \
    -Dplatforms=egl \
    -Dvenus=true \
    -Drender-server=true \
    -Dvulkan-dload=true \
    -Dvulkan-preload=false \
    -Dvideo=false \
    -Dtests=false

meson compile -C "$BUILD_DIR"
DESTDIR="$STAGE_DIR" meson install -C "$BUILD_DIR"

LIB_DIR="$STAGE_DIR/usr/lib"
# Upstream installs to libexec/; some packaging layouts nest under
# libexec/virglrenderer/. Accept either so staging stays version-agnostic.
SERVER=""
for candidate in \
    "$STAGE_DIR/usr/libexec/virgl_render_server" \
    "$STAGE_DIR/usr/libexec/virglrenderer/virgl_render_server"; do
    if [[ -x "$candidate" ]]; then
        SERVER="$candidate"
        break
    fi
done
[[ -f "$LIB_DIR/libvirglrenderer.so.1" ]] || {
    echo "error: build did not produce libvirglrenderer.so.1" >&2
    exit 1
}
[[ -n "$SERVER" ]] || {
    echo "error: build did not produce an executable virgl_render_server" >&2
    exit 1
}

EPOXY_LIB_DIR="$(pkg-config --variable=libdir epoxy)"
[[ -f "$EPOXY_LIB_DIR/libepoxy.so.0" ]] || {
    echo "error: pkg-config epoxy did not locate libepoxy.so.0" >&2
    exit 1
}

rm -f "$OUTPUT_DIR"/libvirglrenderer.so*
cp -a "$LIB_DIR"/libvirglrenderer.so* "$OUTPUT_DIR/"
rm -f "$OUTPUT_DIR"/libepoxy.so*
cp -a "$EPOXY_LIB_DIR"/libepoxy.so* "$OUTPUT_DIR/"
cp "$SERVER" "$OUTPUT_DIR/virgl_render_server"
chmod +x "$OUTPUT_DIR/virgl_render_server"

cat >"$OUTPUT_DIR/virglrenderer.provenance" <<EOF
# Generated by scripts/build-virglrenderer-linux.sh.
version=${VERSION}
source_url=${SOURCE_URL}
source_sha256=${SOURCE_SHA256}
build_arch=${ARCH}
platforms=egl
venus=true
render_server=true
vulkan_dload=true
vulkan_preload=false
video=false
tests=false
EOF

echo "Staged virglrenderer ${VERSION} in $OUTPUT_DIR"
